version: '2'

services:
  media_gallery:
      image: python:3.6
      container_name: media_gallery
      volumes:
        - .:/workspace
      working_dir: /workspace
      environment:
          - TZ=Asia/Shanghai
          - DJANGO_SETTINGS_MODULE=media_gallery.settings_deploy
      command: >
          bash -c "pip install -r requirements.txt
          && ./manage.py collectstatic --noinput
          && daphne -b 0.0.0.0 -p 7000 media_gallery.asgi:application"
      ports:
          - 7800:7000
      depends_on:
        - webrtc-star

  webrtc-star:
      image: libp2p/js-libp2p-webrtc-star
      container_name: webrtc-star
      ports:
          - 7890:9090
