version: '2'

services:
  meida_gallery:
      image: python:3.6
      container_name: meida_gallery
      restart: always
      volumes:
        - .:/workspace
      working_dir: /workspace
      environment:
          - TZ=Asia/Shanghai
          - DJANGO_SETTINGS_MODULE=media_gallery.settings_deploy
      command: >
          bash -c "pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
          && daphne -b 0.0.0.0 -p 7000 media_gallery.asgi:application"
      ports:
          - 7800:7000
