from utils.encrypt import free

ZGDY_API_USER_INFO = free('aHR0cHM6Ly93d3cuaWVzZG91eWluLmNvbS93ZWIvYXBpL3YyL3VzZXIvaW5mby8=')
ICE_SERVERS_LIST_JSON_ENCODE = free('W3sidXJscyI6IFsidHVybjp0dXJuLmRpc3QucHViOjM0NzgiXSwgInVzZXJuYW1lIjogInR1cm4iLCAiY3JlZGVudGlhbCI6ICJ0cnVzdG1lIn0seyJ1cmxzIjogWyJzdHVuOnN0dW4uZGlzdC5wdWI6MzQ3OCJdLCAidXNlcm5hbWUiOiAiIiwgImNyZWRlbnRpYWwiOiAiIn1d')
